export const timezones = [
  { value: 'Pacific/Midway', label: '(GMT-11:00) Midway Island, Samoa' },
  { value: 'Pacific/Honolulu', label: '(GMT-10:00) Hawaii' },
  { value: 'America/Anchorage', label: '(GMT-09:00) Alaska' },
  { value: 'America/Los_Angeles', label: '(GMT-08:00) Pacific Time (US & Canada)' },
  { value: 'America/Phoenix', label: '(GMT-07:00) Arizona' },
  { value: 'America/Denver', label: '(GMT-07:00) Mountain Time (US & Canada)' },
  { value: 'America/Chicago', label: '(GMT-06:00) Central Time (US & Canada)' },
  { value: 'America/Mexico_City', label: '(GMT-06:00) Mexico City' },
  { value: 'America/Regina', label: '(GMT-06:00) Saskatchewan' },
  { value: 'America/New_York', label: '(GMT-05:00) Eastern Time (US & Canada)' },
  { value: 'America/Bogota', label: '(GMT-05:00) Bogota, Lima, Quito' },
  { value: 'America/Caracas', label: '(GMT-04:00) Caracas, La Paz' },
  { value: 'America/Halifax', label: '(GMT-04:00) Atlantic Time (Canada)' },
  { value: 'America/Santiago', label: '(GMT-04:00) Santiago' },
  { value: 'America/St_Johns', label: '(GMT-03:30) Newfoundland' },
  { value: 'America/Argentina/Buenos_Aires', label: '(GMT-03:00) Buenos Aires, Georgetown' },
  { value: 'America/Sao_Paulo', label: '(GMT-03:00) Brasilia' },
  { value: 'Atlantic/South_Georgia', label: '(GMT-02:00) Mid-Atlantic' },
  { value: 'Atlantic/Azores', label: '(GMT-01:00) Azores' },
  { value: 'Europe/London', label: '(GMT+00:00) London, Dublin, Edinburgh' },
  { value: 'Europe/Berlin', label: '(GMT+01:00) Berlin, Rome, Paris, Madrid' },
  { value: 'Europe/Athens', label: '(GMT+02:00) Athens, Helsinki, Istanbul' },
  { value: 'Europe/Moscow', label: '(GMT+03:00) Moscow, St. Petersburg' },
  { value: 'Asia/Dubai', label: '(GMT+04:00) Abu Dhabi, Muscat' },
  { value: 'Asia/Karachi', label: '(GMT+05:00) Islamabad, Karachi' },
  { value: 'Asia/Kolkata', label: '(GMT+05:30) Chennai, Kolkata, Mumbai' },
  { value: 'Asia/Dhaka', label: '(GMT+06:00) Dhaka' },
  { value: 'Asia/Bangkok', label: '(GMT+07:00) Bangkok, Hanoi, Jakarta' },
  { value: 'Asia/Hong_Kong', label: '(GMT+08:00) Beijing, Hong Kong, Singapore' },
  { value: 'Asia/Tokyo', label: '(GMT+09:00) Tokyo, Seoul' },
  { value: 'Australia/Adelaide', label: '(GMT+09:30) Adelaide' },
  { value: 'Australia/Sydney', label: '(GMT+10:00) Sydney, Melbourne, Brisbane' },
  { value: 'Pacific/Auckland', label: '(GMT+12:00) Auckland, Wellington' },
] as const

export const languages = [
  { value: 'en', label: 'English' },
  { value: 'es', label: 'Spanish' },
  { value: 'fr', label: 'French' },
  { value: 'de', label: 'German' },
  { value: 'it', label: 'Italian' },
  { value: 'pt', label: 'Portuguese' },
  { value: 'ru', label: 'Russian' },
  { value: 'ja', label: 'Japanese' },
  { value: 'ko', label: 'Korean' },
  { value: 'zh', label: 'Chinese' },
] as const

export const workoutTimes = [
  { value: '05:00', label: '5:00 AM - Early Morning' },
  { value: '06:00', label: '6:00 AM - Morning' },
  { value: '07:00', label: '7:00 AM - Morning' },
  { value: '08:00', label: '8:00 AM - Morning' },
  { value: '09:00', label: '9:00 AM - Mid-Morning' },
  { value: '10:00', label: '10:00 AM - Mid-Morning' },
  { value: '11:00', label: '11:00 AM - Late Morning' },
  { value: '12:00', label: '12:00 PM - Noon' },
  { value: '13:00', label: '1:00 PM - Early Afternoon' },
  { value: '14:00', label: '2:00 PM - Afternoon' },
  { value: '15:00', label: '3:00 PM - Afternoon' },
  { value: '16:00', label: '4:00 PM - Late Afternoon' },
  { value: '17:00', label: '5:00 PM - Evening' },
  { value: '18:00', label: '6:00 PM - Evening' },
  { value: '19:00', label: '7:00 PM - Evening' },
  { value: '20:00', label: '8:00 PM - Night' },
  { value: '21:00', label: '9:00 PM - Night' },
] as const